"""
UCC Intelligence Platform Server Script

Visible name:
    UCC Analytics - Placeholder Preview

Script type:
    API

API method:
    ucc_analytics_placeholder_preview

Purpose:
    Return clearly labelled dummy preview data for Criteria 1–3 and 6–7.

Important:
    This script does not query operational DocTypes.
    Criteria 4 and 5 remain connected to their live Server Scripts.
    Allow Guest must remain disabled.
"""

PREVIEW_DATA = {'criterion_1': {'criterion': '1',
                 'title': 'Leadership and Strategic Planning',
                 'status': 'dummy_preview',
                 'demo_only': True,
                 'policy_set': [],
                 'kpis': [{'label': 'Governance meetings', 'value': '12', 'note': 'Current preview year'},
                          {'label': 'Strategic objectives', 'value': '8', 'note': 'Approved objectives'},
                          {'label': 'Objectives on track', 'value': '75%', 'note': '6 of 8 objectives'},
                          {'label': 'Policies reviewed', 'value': '18', 'note': 'Review cycle complete'},
                          {'label': 'Questions answered', 'value': '8', 'note': 'Preview Q&A'},
                          {'label': 'Open exceptions', 'value': '4', 'note': 'Dummy follow-up items'}],
                 'sources': [{'key': 'Board Meeting',
                              'purpose': 'Governance decisions and action tracking',
                              'status': 'Demo available'},
                             {'key': 'Strategic Plan',
                              'purpose': 'Objectives, initiatives and targets',
                              'status': 'Demo available'},
                             {'key': 'Policies and Procedures',
                              'purpose': 'Policy ownership and review dates',
                              'status': 'Demo available'},
                             {'key': 'Management Review',
                              'purpose': 'Leadership review and follow-up',
                              'status': 'Demo available'}],
                 'records': [{'name': 'GOV-0001', 'description': 'Board action review', 'status': 'Good'},
                             {'name': 'GOV-0002', 'description': 'Policy ownership update', 'status': 'Warning'},
                             {'name': 'STR-0003', 'description': 'Strategic initiative milestone', 'status': 'Risk'},
                             {'name': 'STR-0004', 'description': 'Management review follow-up', 'status': 'Good'}],
                 'sections': {'overview': {'title': 'Overview',
                                           'policy': None,
                                           'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                           'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                           'charts': [{'id': 'criterion_1-overview-targets',
                                                       'title': 'Target Gap Summary',
                                                       'type': 'bar'},
                                                      {'id': 'criterion_1-overview-sources',
                                                       'title': 'Source Availability',
                                                       'type': 'donut'}],
                                           'questions': [{'question': 'Are governance responsibilities formally '
                                                                      'assigned?',
                                                          'answer': 'Yes — 92% of preview governance roles have an '
                                                                    'assigned owner.',
                                                          'source': 'Board Meeting / Policies and Procedures',
                                                          'status': 'Good'},
                                                         {'question': 'Are strategic objectives monitored regularly?',
                                                          'answer': '6 of 8 preview objectives are on track.',
                                                          'source': 'Strategic Plan',
                                                          'status': 'Warning'},
                                                         {'question': 'Are leadership actions closed on time?',
                                                          'answer': '84% of preview actions were closed by the target '
                                                                    'date.',
                                                          'source': 'Management Review',
                                                          'status': 'Warning'}]},
                              '1.1': {'title': 'Leadership and Corporate Governance',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_1-11-coverage',
                                                  'title': 'Leadership and Corporate Governance Control Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_1-11-status',
                                                  'title': 'Leadership and Corporate Governance Status Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is leadership and corporate governance operating as '
                                                                 'designed?',
                                                     'answer': 'Preview result: 90% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Leadership and Corporate Governance register',
                                                     'status': 'Good'},
                                                    {'question': 'Which leadership and corporate governance records '
                                                                 'need follow-up?',
                                                     'answer': 'Preview result: 3 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]},
                              '1.2': {'title': 'Strategic Planning',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_1-12-coverage',
                                                  'title': 'Strategic Planning Control Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_1-12-status',
                                                  'title': 'Strategic Planning Status Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is strategic planning operating as designed?',
                                                     'answer': 'Preview result: 85% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Strategic Planning register',
                                                     'status': 'Good'},
                                                    {'question': 'Which strategic planning records need follow-up?',
                                                     'answer': 'Preview result: 4 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]}},
                 'note': 'Dummy preview data only. Do not use for operational, compliance or regulatory reporting.'},
 'criterion_2': {'criterion': '2',
                 'title': 'Corporate Administration',
                 'status': 'dummy_preview',
                 'demo_only': True,
                 'policy_set': [],
                 'kpis': [{'label': 'Employees in scope', 'value': '86', 'note': 'Preview workforce'},
                          {'label': 'Training completion', 'value': '91%', 'note': 'Required training'},
                          {'label': 'Communications issued', 'value': '24', 'note': 'Current preview year'},
                          {'label': 'Knowledge assets', 'value': '42', 'note': 'Controlled documents'},
                          {'label': 'Feedback cases', 'value': '18', 'note': 'Preview cases'},
                          {'label': 'Open exceptions', 'value': '7', 'note': 'Dummy follow-up items'}],
                 'sources': [{'key': 'Employee',
                              'purpose': 'Employee profile and role information',
                              'status': 'Demo available'},
                             {'key': 'Training Event',
                              'purpose': 'Training attendance and completion',
                              'status': 'Demo available'},
                             {'key': 'Communication Log',
                              'purpose': 'Internal and external communication',
                              'status': 'Demo available'},
                             {'key': 'Feedback Case',
                              'purpose': 'Feedback, response and closure',
                              'status': 'Demo available'}],
                 'records': [{'name': 'HR-0007', 'description': 'Mandatory training renewal', 'status': 'Warning'},
                             {'name': 'COM-0012', 'description': 'Student notice publication', 'status': 'Good'},
                             {'name': 'KM-0008', 'description': 'Document review overdue', 'status': 'Risk'},
                             {'name': 'FB-0018', 'description': 'Feedback closure follow-up', 'status': 'Warning'}],
                 'sections': {'overview': {'title': 'Overview',
                                           'policy': None,
                                           'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                           'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                           'charts': [{'id': 'criterion_2-overview-targets',
                                                       'title': 'Target Gap Summary',
                                                       'type': 'bar'},
                                                      {'id': 'criterion_2-overview-sources',
                                                       'title': 'Source Availability',
                                                       'type': 'donut'}],
                                           'questions': [{'question': 'Are required staff competencies maintained?',
                                                          'answer': '91% of preview mandatory training is complete.',
                                                          'source': 'Employee / Training Event',
                                                          'status': 'Warning'},
                                                         {'question': 'Are controlled communications issued on time?',
                                                          'answer': '22 of 24 preview communications met the target '
                                                                    'date.',
                                                          'source': 'Communication Log',
                                                          'status': 'Good'},
                                                         {'question': 'Are feedback cases closed within the service '
                                                                      'target?',
                                                          'answer': '78% of preview cases met the closure target.',
                                                          'source': 'Feedback Case',
                                                          'status': 'Warning'}]},
                              '2.1': {'title': 'Human Resource',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_2-21-coverage',
                                                  'title': 'Human Resource Control Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_2-21-status',
                                                  'title': 'Human Resource Status Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is human resource operating as designed?',
                                                     'answer': 'Preview result: 89% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Human Resource register',
                                                     'status': 'Good'},
                                                    {'question': 'Which human resource records need follow-up?',
                                                     'answer': 'Preview result: 3 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]},
                              '2.2': {'title': 'Communication',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_2-22-coverage',
                                                  'title': 'Communication Control Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_2-22-status',
                                                  'title': 'Communication Status Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is communication operating as designed?',
                                                     'answer': 'Preview result: 84% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Communication register',
                                                     'status': 'Warning'},
                                                    {'question': 'Which communication records need follow-up?',
                                                     'answer': 'Preview result: 4 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]},
                              '2.3': {'title': 'Data, Information and Knowledge Management',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_2-23-coverage',
                                                  'title': 'Data, Information and Knowledge Management Control '
                                                           'Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_2-23-status',
                                                  'title': 'Data, Information and Knowledge Management Status '
                                                           'Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is data, information and knowledge management '
                                                                 'operating as designed?',
                                                     'answer': 'Preview result: 79% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Data, Information and Knowledge Management '
                                                               'register',
                                                     'status': 'Warning'},
                                                    {'question': 'Which data, information and knowledge management '
                                                                 'records need follow-up?',
                                                     'answer': 'Preview result: 5 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]},
                              '2.4': {'title': 'Feedback Management',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_2-24-coverage',
                                                  'title': 'Feedback Management Control Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_2-24-status',
                                                  'title': 'Feedback Management Status Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is feedback management operating as designed?',
                                                     'answer': 'Preview result: 74% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Feedback Management register',
                                                     'status': 'Warning'},
                                                    {'question': 'Which feedback management records need follow-up?',
                                                     'answer': 'Preview result: 6 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]}},
                 'note': 'Dummy preview data only. Do not use for operational, compliance or regulatory reporting.'},
 'criterion_3': {'criterion': '3',
                 'title': 'External Recruitment Agents',
                 'status': 'dummy_preview',
                 'demo_only': True,
                 'policy_set': [{'code': 'PPD-SES-SL-3.1.1',
                                 'version': '1.2',
                                 'title': 'Selection and Appointment of External Recruitment Agents',
                                 'updated': '15 January 2026'},
                                {'code': 'PPD-SES-SL-3.2.1',
                                 'version': '1.2',
                                 'title': 'Management and Evaluation of Recruitment Agents',
                                 'updated': '15 January 2026'}],
                 'kpis': [{'label': 'Agents in portfolio', 'value': '18', 'note': 'Dummy agent register'},
                          {'label': 'Selection evidence complete',
                           'value': '89%',
                           'note': 'Application, screening and scoring'},
                          {'label': 'Valid contracts and NDA', 'value': '83%', 'note': 'Appointment controls'},
                          {'label': 'Evaluation pass rate', 'value': '78%', 'note': 'Minimum passing score 3.5'},
                          {'label': 'Renewals due', 'value': '4', 'note': 'June and December checkpoints'},
                          {'label': 'Open exceptions', 'value': '7', 'note': 'Dummy follow-up items'}],
                 'sources': [{'key': 'Agent DocType',
                              'purpose': 'Agent profile, rating, approval, contract and status',
                              'status': 'Demo available'},
                             {'key': 'Recruitment Agent Application Form',
                              'purpose': 'Identification and screening evidence',
                              'status': 'Demo available'},
                             {'key': 'Agent Contract and NDA',
                              'purpose': 'Appointment and confidentiality controls',
                              'status': 'Demo available'},
                             {'key': 'Agent Claim Form DocType',
                              'purpose': 'Commission and claim records',
                              'status': 'Demo available'},
                             {'key': 'Material Vetting DocType',
                              'purpose': 'Promotional-material approval',
                              'status': 'Demo available'},
                             {'key': 'Student Applicant',
                              'purpose': 'Agent-attributed applicant outcomes',
                              'status': 'Demo available'},
                             {'key': 'Feedback and Complaint Records',
                              'purpose': 'Complaint, breach and follow-up evidence',
                              'status': 'Demo available'}],
                 'records': [{'name': 'AGT-0004',
                              'description': 'Background check evidence incomplete',
                              'status': 'Warning'},
                             {'name': 'AGT-0007',
                              'description': 'Contract renewal due at June checkpoint',
                              'status': 'Warning'},
                             {'name': 'AGT-0011', 'description': 'Onboarding training completed', 'status': 'Good'},
                             {'name': 'AGT-0014', 'description': 'Performance score below 3.5', 'status': 'Risk'},
                             {'name': 'AGT-0018',
                              'description': 'Promotional material pending approval',
                              'status': 'Warning'}],
                 'sections': {'overview': {'title': 'Criterion 3 Overview',
                                           'policy': {'code': 'Criterion 3 policy set',
                                                      'version': '2 mapped documents',
                                                      'title': 'External Recruitment Agents'},
                                           'source_summary': {'available': 7, 'total': 7, 'issues': 0},
                                           'metric_summary': {'available': 5, 'total': 5, 'issues': 0},
                                           'charts': [{'id': 'c3-overview-lifecycle',
                                                       'title': 'Agent Lifecycle Coverage',
                                                       'type': 'lifecycle'},
                                                      {'id': 'c3-overview-policy',
                                                       'title': 'Policy Control Coverage',
                                                       'type': 'donut'},
                                                      {'id': 'c3-overview-health',
                                                       'title': 'Agent Control Health',
                                                       'type': 'radar'},
                                                      {'id': 'c3-overview-renewal',
                                                       'title': 'Renewal and Evaluation Trend',
                                                       'type': 'trend'},
                                                      {'id': 'c3-overview-exceptions',
                                                       'title': 'Open Exception Profile',
                                                       'type': 'bar'}],
                                           'questions': [{'question': 'Are agents selected using the approved '
                                                                      'identification and screening process?',
                                                          'answer': '16 of 18 dummy agents have complete application, '
                                                                    'screening and rating evidence.',
                                                          'source': 'PPD-SES-SL-3.1.1 / Agent DocType',
                                                          'status': 'Warning'},
                                                         {'question': 'Are appointed agents protected by current '
                                                                      'contracts and NDAs?',
                                                          'answer': '15 of 18 dummy agents have both documents '
                                                                    'current.',
                                                          'source': 'Agent Contract and NDA',
                                                          'status': 'Warning'},
                                                         {'question': 'Are agent evaluations completed before renewal '
                                                                      'decisions?',
                                                          'answer': '14 of 18 dummy agents have a current evaluation.',
                                                          'source': 'PPD-SES-SL-3.2.1 / Agent DocType',
                                                          'status': 'Warning'}]},
                              '3.1.1': {'title': 'Selection and Appointment of External Recruitment Agents',
                                        'policy': {'code': 'PPD-SES-SL-3.1.1',
                                                   'version': '1.2',
                                                   'title': 'Selection and Appointment of External Recruitment Agents'},
                                        'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                        'metric_summary': {'available': 7, 'total': 7, 'issues': 0},
                                        'charts': [{'id': 'c311-identification',
                                                    'title': 'Identification Pathways',
                                                    'type': 'donut'},
                                                   {'id': 'c311-screening',
                                                    'title': 'Selection and Screening Funnel',
                                                    'type': 'funnel'},
                                                   {'id': 'c311-weighting',
                                                    'title': 'Selection Criteria Weighting',
                                                    'type': 'radar'},
                                                   {'id': 'c311-score',
                                                    'title': 'Selection Score Distribution',
                                                    'type': 'bar'},
                                                   {'id': 'c311-approval',
                                                    'title': 'Approval and Background Check',
                                                    'type': 'lifecycle'},
                                                   {'id': 'c311-contract',
                                                    'title': 'Contract and NDA Readiness',
                                                    'type': 'matrix'},
                                                   {'id': 'c311-listing',
                                                    'title': 'Agent Listing and Status',
                                                    'type': 'donut'}],
                                        'questions': [{'question': 'Do all identified agents pass both initial and '
                                                                   'final screening?',
                                                       'answer': '20 of 26 dummy applications reached final rating; 6 '
                                                                 'require no further engagement.',
                                                       'source': 'Recruitment Agent Application Form / Agent DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Is the minimum passing rate of 3.5 applied before '
                                                                   'appointment?',
                                                       'answer': '16 dummy agents meet or exceed the 3.5 appointment '
                                                                 'threshold.',
                                                       'source': 'Agent DocType rating',
                                                       'status': 'Good'},
                                                      {'question': 'Are contract scope, authority and confidentiality '
                                                                   'controls recorded?',
                                                       'answer': '15 of 18 dummy agent files are complete.',
                                                       'source': 'Agent Contract and NDA',
                                                       'status': 'Warning'}]},
                              '3.2.1': {'title': 'Management and Evaluation of Recruitment Agents',
                                        'policy': {'code': 'PPD-SES-SL-3.2.1',
                                                   'version': '1.2',
                                                   'title': 'Management and Evaluation of Recruitment Agents'},
                                        'source_summary': {'available': 7, 'total': 7, 'issues': 0},
                                        'metric_summary': {'available': 7, 'total': 7, 'issues': 0},
                                        'charts': [{'id': 'c321-onboarding',
                                                    'title': 'Agent Onboarding Funnel',
                                                    'type': 'funnel'},
                                                   {'id': 'c321-training',
                                                    'title': 'Training Coverage',
                                                    'type': 'radar'},
                                                   {'id': 'c321-service',
                                                    'title': 'Service Delivery Controls',
                                                    'type': 'matrix'},
                                                   {'id': 'c321-evaluation',
                                                    'title': 'Performance Evaluation Distribution',
                                                    'type': 'bar'},
                                                   {'id': 'c321-renewal',
                                                    'title': 'Renewal Checkpoint Flow',
                                                    'type': 'lifecycle'},
                                                   {'id': 'c321-complaints',
                                                    'title': 'Complaints and Breaches',
                                                    'type': 'donut'},
                                                   {'id': 'c321-offboarding',
                                                    'title': 'Offboarding and Exit Security',
                                                    'type': 'flow'}],
                                        'questions': [{'question': 'Are active agents trained and kept current on '
                                                                   'course and policy changes?',
                                                       'answer': '16 of 18 dummy agents have current onboarding or '
                                                                 'annual training evidence.',
                                                       'source': 'Agent file / training evidence',
                                                       'status': 'Warning'},
                                                      {'question': 'Are renewal decisions based on documented '
                                                                   'performance?',
                                                       'answer': '14 of 18 dummy agents have a completed evaluation '
                                                                 'before the next checkpoint.',
                                                       'source': 'Agent DocType monitor and review',
                                                       'status': 'Warning'},
                                                      {'question': 'Are complaints, breaches and offboarding actions '
                                                                   'traceable?',
                                                       'answer': 'All 4 dummy offboarding cases have a decision '
                                                                 'record; one access-revocation record remains open.',
                                                       'source': 'Complaint records / Agent DocType',
                                                       'status': 'Warning'}]}},
                 'note': 'Dummy preview data only. Do not use for operational, compliance or regulatory reporting.'},
 'criterion_6': {'criterion': '6',
                 'title': 'Quality Assurance, Innovation and Continual Improvement',
                 'status': 'dummy_preview',
                 'demo_only': True,
                 'policy_set': [{'code': 'PPD-SGL-SQ-6.1.1',
                                 'version': '1.2',
                                 'title': 'Internal Assessment and Quality Audits',
                                 'updated': '15 January 2026'},
                                {'code': 'PPD-SGL-SQ-6.2.1',
                                 'version': '1.3',
                                 'title': 'Management Review',
                                 'updated': '10 April 2026'},
                                {'code': 'PPD-SGL-SQ-6.3.1',
                                 'version': '1.2',
                                 'title': 'Innovation and Continual Improvement',
                                 'updated': '15 January 2026'},
                                {'code': 'PPD-OE-FN-6.4.1',
                                 'version': '1.2',
                                 'title': "Provider's Accreditation and Evaluation",
                                 'updated': '15 January 2026'},
                                {'code': 'PPD-SGL-SQ-6.5.3',
                                 'version': '1.2',
                                 'title': 'Hazard Identification and Risk Assessment',
                                 'updated': '15 January 2026'}],
                 'kpis': [{'label': 'Quality activities', 'value': '42', 'note': 'Dummy policy-linked records'},
                          {'label': 'Controls complete', 'value': '84%', 'note': 'Evidence and approval coverage'},
                          {'label': 'Actions closed', 'value': '76%', 'note': 'Corrective and improvement actions'},
                          {'label': 'Reviews on schedule', 'value': '88%', 'note': 'Quality calendar'},
                          {'label': 'Policy sources mapped', 'value': '5', 'note': 'Attached Criterion 6 documents'},
                          {'label': 'Open exceptions', 'value': '11', 'note': 'Dummy follow-up items'}],
                 'sources': [{'key': 'Oversight Framework DocType',
                              'purpose': 'Audit programme, scope, findings and reports',
                              'status': 'Demo available'},
                             {'key': 'Responsibilities DocType',
                              'purpose': 'Auditor qualification and committee assignment',
                              'status': 'Demo available'},
                             {'key': 'Management Review DocType',
                              'purpose': 'Review inputs, attendance, decisions and outputs',
                              'status': 'Demo available'},
                             {'key': 'Quality Meeting DocType',
                              'purpose': 'Meeting evidence and review records',
                              'status': 'Demo available'},
                             {'key': 'Quality Action DocType',
                              'purpose': 'Corrective, preventive and improvement actions',
                              'status': 'Demo available'},
                             {'key': 'Quality Performance Outcomes DocType',
                              'purpose': 'QIPI indicators and outcomes',
                              'status': 'Demo available'},
                             {'key': 'Provider DocType',
                              'purpose': 'Provider accreditation and compliance evidence',
                              'status': 'Demo available'},
                             {'key': 'Provider Rating DocType',
                              'purpose': 'Provider performance evaluation',
                              'status': 'Demo available'},
                             {'key': 'Purchase Receipt / Quality Inspection',
                              'purpose': 'Delivery and inspection evidence',
                              'status': 'Demo available'},
                             {'key': 'Risk Register and Mitigation Plans DocType',
                              'purpose': 'Hazards, risk index and treatment',
                              'status': 'Demo available'},
                             {'key': 'Helpdesk-Ticket',
                              'purpose': 'Hazard and incident reporting',
                              'status': 'Demo available'},
                             {'key': 'Business Continuity and Disaster Recovery DocType',
                              'purpose': 'BC/DR readiness and testing',
                              'status': 'Demo available'}],
                 'records': [{'name': 'AUD-2026-04',
                              'description': 'Corrective action verification due',
                              'status': 'Warning'},
                             {'name': 'MR-2026-01',
                              'description': 'Management-review action awaiting owner update',
                              'status': 'Warning'},
                             {'name': 'QA-0042',
                              'description': 'Innovation outcome validation overdue',
                              'status': 'Risk'},
                             {'name': 'PRV-0018',
                              'description': 'Provider PDPA undertaking missing',
                              'status': 'Warning'},
                             {'name': 'RISK-0031', 'description': 'High risk treatment in progress', 'status': 'Risk'},
                             {'name': 'BCDR-0003',
                              'description': 'Disaster recovery exercise completed',
                              'status': 'Good'}],
                 'sections': {'overview': {'title': 'Criterion 6 Overview',
                                           'policy': {'code': 'Criterion 6 policy set',
                                                      'version': '5 mapped documents',
                                                      'title': 'Quality Assurance, Innovation and Continual '
                                                               'Improvement'},
                                           'source_summary': {'available': 12, 'total': 12, 'issues': 0},
                                           'metric_summary': {'available': 6, 'total': 6, 'issues': 0},
                                           'charts': [{'id': 'c6-overview-cycle',
                                                       'title': 'Quality Management Cycle',
                                                       'type': 'lifecycle'},
                                                      {'id': 'c6-overview-policy',
                                                       'title': 'Policy Evidence Coverage',
                                                       'type': 'donut'},
                                                      {'id': 'c6-overview-health',
                                                       'title': 'Quality System Health',
                                                       'type': 'radar'},
                                                      {'id': 'c6-overview-calendar',
                                                       'title': 'Quality Calendar Completion',
                                                       'type': 'trend'},
                                                      {'id': 'c6-overview-actions',
                                                       'title': 'Action Status',
                                                       'type': 'bar'},
                                                      {'id': 'c6-overview-readiness',
                                                       'title': 'Source Readiness',
                                                       'type': 'matrix'}],
                                           'questions': [{'question': 'Are internal assessments completed and findings '
                                                                      'closed?',
                                                          'answer': '7 of 8 dummy audits are complete; 3 corrective '
                                                                    'actions remain open.',
                                                          'source': 'PPD-SGL-SQ-6.1.1 / Oversight Framework',
                                                          'status': 'Warning'},
                                                         {'question': 'Does Management Review produce owned and '
                                                                      'tracked actions?',
                                                          'answer': '10 of 12 dummy actions have an owner and target '
                                                                    'date.',
                                                          'source': 'PPD-SGL-SQ-6.2.1 / Quality Action',
                                                          'status': 'Warning'},
                                                         {'question': 'Are improvement, provider and risk outcomes '
                                                                      'measured?',
                                                          'answer': 'Dummy QIPI, provider rating and residual-risk '
                                                                    'measures are available across the preview.',
                                                          'source': 'Criterion 6 policy set',
                                                          'status': 'Good'}]},
                              '6.1.1': {'title': 'Internal Assessment and Quality Audits',
                                        'policy': {'code': 'PPD-SGL-SQ-6.1.1',
                                                   'version': '1.2',
                                                   'title': 'Internal Assessment and Quality Audits'},
                                        'source_summary': {'available': 5, 'total': 5, 'issues': 0},
                                        'metric_summary': {'available': 6, 'total': 6, 'issues': 0},
                                        'charts': [{'id': 'c611-programme',
                                                    'title': 'Annual Audit Programme',
                                                    'type': 'donut'},
                                                   {'id': 'c611-scope',
                                                    'title': 'Audit Scope Coverage',
                                                    'type': 'radar'},
                                                   {'id': 'c611-lifecycle',
                                                    'title': 'Audit Lifecycle',
                                                    'type': 'funnel'},
                                                   {'id': 'c611-auditors',
                                                    'title': 'Auditor Qualification and Independence',
                                                    'type': 'matrix'},
                                                   {'id': 'c611-findings',
                                                    'title': 'Audit Findings by Severity',
                                                    'type': 'bar'},
                                                   {'id': 'c611-cap',
                                                    'title': 'Corrective Action Closure',
                                                    'type': 'trend'}],
                                        'questions': [{'question': 'Is the annual audit programme complete and '
                                                                   'approved?',
                                                       'answer': '10 of 11 dummy audits have approved scope and dates.',
                                                       'source': 'Oversight Framework DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Are auditors qualified and independent of the '
                                                                   'audited area?',
                                                       'answer': 'All dummy assignments pass independence checks; one '
                                                                 'CPD record requires renewal.',
                                                       'source': 'Responsibilities DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Are corrective actions verified before closure?',
                                                       'answer': '10 of 18 dummy findings are closed after '
                                                                 'verification.',
                                                       'source': 'Quality Action DocType',
                                                       'status': 'Warning'}]},
                              '6.2.1': {'title': 'Management Review',
                                        'policy': {'code': 'PPD-SGL-SQ-6.2.1',
                                                   'version': '1.3',
                                                   'title': 'Management Review'},
                                        'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                        'metric_summary': {'available': 6, 'total': 6, 'issues': 0},
                                        'charts': [{'id': 'c621-thesis',
                                                    'title': 'THESIS Review Coverage',
                                                    'type': 'radar'},
                                                   {'id': 'c621-preparation',
                                                    'title': 'Management Review Preparation',
                                                    'type': 'funnel'},
                                                   {'id': 'c621-inputs',
                                                    'title': 'Review Input Completeness',
                                                    'type': 'matrix'},
                                                   {'id': 'c621-outputs', 'title': 'Review Outputs', 'type': 'donut'},
                                                   {'id': 'c621-ageing', 'title': 'Action Ageing', 'type': 'bar'},
                                                   {'id': 'c621-effectiveness',
                                                    'title': 'Action Effectiveness',
                                                    'type': 'trend'}],
                                        'questions': [{'question': 'Are all THESIS areas reviewed using current '
                                                                   'evidence?',
                                                       'answer': 'Five of six dummy THESIS domains exceed 75% evidence '
                                                                 'coverage.',
                                                       'source': 'Management Review DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Do review outputs include owners and timelines?',
                                                       'answer': '10 of 12 dummy actions have both an owner and a '
                                                                 'target date.',
                                                       'source': 'Quality Action DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Is action effectiveness checked at the next '
                                                                   'review?',
                                                       'answer': '8 dummy actions have verified effectiveness; 2 '
                                                                 'require further action.',
                                                       'source': 'Management Review / Quality Action',
                                                       'status': 'Warning'}]},
                              '6.3.1': {'title': 'Innovation and Continual Improvement',
                                        'policy': {'code': 'PPD-SGL-SQ-6.3.1',
                                                   'version': '1.2',
                                                   'title': 'Innovation and Continual Improvement'},
                                        'source_summary': {'available': 2, 'total': 2, 'issues': 0},
                                        'metric_summary': {'available': 6, 'total': 6, 'issues': 0},
                                        'charts': [{'id': 'c631-types',
                                                    'title': 'Innovation Type Mix',
                                                    'type': 'donut'},
                                                   {'id': 'c631-lifecycle',
                                                    'title': 'Improvement Initiative Lifecycle',
                                                    'type': 'funnel'},
                                                   {'id': 'c631-investment',
                                                    'title': 'Innovation Performance Categories',
                                                    'type': 'radar'},
                                                   {'id': 'c631-qipi', 'title': 'QIPI Outcome Trend', 'type': 'trend'},
                                                   {'id': 'c631-impact',
                                                    'title': 'Before and After Impact',
                                                    'type': 'gauge'},
                                                   {'id': 'c631-status',
                                                    'title': 'Improvement Action Status',
                                                    'type': 'matrix'}],
                                        'questions': [{'question': 'Are initiatives classified and linked to a defined '
                                                                   'problem or opportunity?',
                                                       'answer': '22 of 24 dummy initiatives contain a problem '
                                                                 'statement and improvement type.',
                                                       'source': 'Quality Action DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Are outcomes measured using before-and-after '
                                                                   'indicators?',
                                                       'answer': '13 dummy initiatives have implementation results; 10 '
                                                                 'have validated outcomes.',
                                                       'source': 'Quality Performance Outcomes DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Is QIPI reviewed during Management Review?',
                                                       'answer': 'The dummy QIPI result is available for the next '
                                                                 'Management Review.',
                                                       'source': 'QIPI / Management Review',
                                                       'status': 'Good'}]},
                              '6.4.1': {'title': "Provider's Accreditation and Evaluation",
                                        'policy': {'code': 'PPD-OE-FN-6.4.1',
                                                   'version': '1.2',
                                                   'title': "Provider's Accreditation and Evaluation"},
                                        'source_summary': {'available': 3, 'total': 3, 'issues': 0},
                                        'metric_summary': {'available': 6, 'total': 6, 'issues': 0},
                                        'charts': [{'id': 'c641-tier',
                                                    'title': 'Provider Tier Profile',
                                                    'type': 'donut'},
                                                   {'id': 'c641-screening',
                                                    'title': 'Provider Accreditation Funnel',
                                                    'type': 'funnel'},
                                                   {'id': 'c641-package',
                                                    'title': 'Compliance Package',
                                                    'type': 'matrix'},
                                                   {'id': 'c641-delivery',
                                                    'title': 'Service Delivery and Purchase Controls',
                                                    'type': 'lifecycle'},
                                                   {'id': 'c641-rating',
                                                    'title': 'Provider Rating Weighting',
                                                    'type': 'radar'},
                                                   {'id': 'c641-outcomes',
                                                    'title': 'Provider Evaluation Outcomes',
                                                    'type': 'donut'}],
                                        'questions': [{'question': 'Are providers classified by tier and screened '
                                                                   'proportionately?',
                                                       'answer': '25 of 27 dummy providers have both tier and '
                                                                 'risk-assessment evidence.',
                                                       'source': 'Provider DocType',
                                                       'status': 'Warning'},
                                                      {'question': 'Are delivery, inspection and satisfaction records '
                                                                   'complete?',
                                                       'answer': '20 of 24 dummy completed purchases have full '
                                                                 'delivery and satisfaction evidence.',
                                                       'source': 'Purchase Receipt / Quality Inspection',
                                                       'status': 'Warning'},
                                                      {'question': 'Are provider continuation decisions based on a '
                                                                   'score of at least 3.5?',
                                                       'answer': '19 dummy providers pass; 2 require an improvement '
                                                                 'plan.',
                                                       'source': 'Provider Rating DocType',
                                                       'status': 'Warning'}]},
                              '6.5.3': {'title': 'Hazard Identification and Risk Assessment',
                                        'policy': {'code': 'PPD-SGL-SQ-6.5.3',
                                                   'version': '1.2',
                                                   'title': 'Hazard Identification and Risk Assessment'},
                                        'source_summary': {'available': 3, 'total': 3, 'issues': 0},
                                        'metric_summary': {'available': 6, 'total': 6, 'issues': 0},
                                        'charts': [{'id': 'c653-reporting',
                                                    'title': 'Hazard Reporting Funnel',
                                                    'type': 'funnel'},
                                                   {'id': 'c653-levels',
                                                    'title': 'Risk Level Distribution',
                                                    'type': 'donut'},
                                                   {'id': 'c653-matrix',
                                                    'title': '5×5 Risk Matrix',
                                                    'type': 'risk-matrix'},
                                                   {'id': 'c653-treatment',
                                                    'title': 'Risk Treatment Lifecycle',
                                                    'type': 'lifecycle'},
                                                   {'id': 'c653-residual',
                                                    'title': 'Residual Risk Trend',
                                                    'type': 'trend'},
                                                   {'id': 'c653-bcdr',
                                                    'title': 'Business Continuity Readiness',
                                                    'type': 'radar'}],
                                        'questions': [{'question': 'Are hazards recorded and assessed using likelihood '
                                                                   'and severity?',
                                                       'answer': '20 of 22 dummy hazards have a calculated risk index.',
                                                       'source': 'Helpdesk-Ticket / Risk Register',
                                                       'status': 'Warning'},
                                                      {'question': 'Are medium and high risks investigated and '
                                                                   'treated?',
                                                       'answer': '14 dummy medium/high risks have an assigned '
                                                                 'treatment; 4 remain under investigation.',
                                                       'source': 'Risk Register and Quality Action',
                                                       'status': 'Warning'},
                                                      {'question': 'Are residual risk and business-continuity controls '
                                                                   'verified?',
                                                       'answer': '7 dummy treatments have residual-risk results; one '
                                                                 'BC/DR exercise remains due.',
                                                       'source': 'Risk Register / BC and DR',
                                                       'status': 'Warning'}]}},
                 'note': 'Dummy preview data only. Do not use for operational, compliance or regulatory reporting.'},
 'criterion_7': {'criterion': '7',
                 'title': 'Performance Outcomes',
                 'status': 'dummy_preview',
                 'demo_only': True,
                 'policy_set': [],
                 'kpis': [{'label': 'Outcome indicators', 'value': '18', 'note': 'Preview scorecard'},
                          {'label': 'Targets achieved', 'value': '72%', 'note': '13 of 18 indicators'},
                          {'label': 'Student outcomes', 'value': '88%', 'note': 'Preview completion'},
                          {'label': 'Graduate outcomes', 'value': '81%', 'note': 'Preview progression'},
                          {'label': 'Stakeholder rating', 'value': '4.3', 'note': 'Five-point scale'},
                          {'label': 'Open gaps', 'value': '6', 'note': 'Dummy follow-up items'}],
                 'sources': [{'key': 'Performance Indicator',
                              'purpose': 'Target and actual outcome values',
                              'status': 'Demo available'},
                             {'key': 'Student Outcome',
                              'purpose': 'Completion and progression',
                              'status': 'Demo available'},
                             {'key': 'Graduate Survey',
                              'purpose': 'Graduate destination and satisfaction',
                              'status': 'Demo available'},
                             {'key': 'Stakeholder Survey',
                              'purpose': 'Employer and stakeholder feedback',
                              'status': 'Demo available'}],
                 'records': [{'name': 'PI-0018', 'description': 'Outcome result not updated', 'status': 'Warning'},
                             {'name': 'SO-0088', 'description': 'Student completion outcome', 'status': 'Good'},
                             {'name': 'GS-0081', 'description': 'Graduate progression result', 'status': 'Good'},
                             {'name': 'SS-0043', 'description': 'Stakeholder improvement action', 'status': 'Risk'}],
                 'sections': {'overview': {'title': 'Overview',
                                           'policy': None,
                                           'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                           'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                           'charts': [{'id': 'criterion_7-overview-targets',
                                                       'title': 'Target Gap Summary',
                                                       'type': 'bar'},
                                                      {'id': 'criterion_7-overview-sources',
                                                       'title': 'Source Availability',
                                                       'type': 'donut'}],
                                           'questions': [{'question': 'Are outcome indicators measured consistently?',
                                                          'answer': '16 of 18 preview indicators have a current '
                                                                    'result.',
                                                          'source': 'Performance Indicator',
                                                          'status': 'Warning'},
                                                         {'question': 'Are performance targets being achieved?',
                                                          'answer': '13 of 18 preview targets are achieved.',
                                                          'source': 'Performance Indicator',
                                                          'status': 'Warning'},
                                                         {'question': 'Are graduate and stakeholder outcomes '
                                                                      'improving?',
                                                          'answer': 'Preview graduate outcomes improved by 6 '
                                                                    'percentage points.',
                                                          'source': 'Graduate Survey / Stakeholder Survey',
                                                          'status': 'Good'}]},
                              '7.1': {'title': 'Measurement of Outcomes',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_7-71-coverage',
                                                  'title': 'Measurement of Outcomes Control Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_7-71-status',
                                                  'title': 'Measurement of Outcomes Status Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is measurement of outcomes operating as designed?',
                                                     'answer': 'Preview result: 84% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Measurement of Outcomes register',
                                                     'status': 'Warning'},
                                                    {'question': 'Which measurement of outcomes records need '
                                                                 'follow-up?',
                                                     'answer': 'Preview result: 3 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]},
                              '7.2': {'title': 'Achievement of Outcomes',
                                      'policy': None,
                                      'source_summary': {'available': 4, 'total': 4, 'issues': 0},
                                      'metric_summary': {'available': 2, 'total': 2, 'issues': 0},
                                      'charts': [{'id': 'criterion_7-72-coverage',
                                                  'title': 'Achievement of Outcomes Control Coverage',
                                                  'type': 'bar'},
                                                 {'id': 'criterion_7-72-status',
                                                  'title': 'Achievement of Outcomes Status Distribution',
                                                  'type': 'donut'}],
                                      'questions': [{'question': 'Is achievement of outcomes operating as designed?',
                                                     'answer': 'Preview result: 79% of dummy controls meet the '
                                                               'expected condition.',
                                                     'source': 'Dummy Achievement of Outcomes register',
                                                     'status': 'Warning'},
                                                    {'question': 'Which achievement of outcomes records need '
                                                                 'follow-up?',
                                                     'answer': 'Preview result: 4 dummy records require review.',
                                                     'source': 'Dummy exception register',
                                                     'status': 'Warning'}]}},
                 'note': 'Dummy preview data only. Do not use for operational, compliance or regulatory reporting.'}}

criterion = str(frappe.form_dict.get("criterion") or "").strip().lower()
section = str(frappe.form_dict.get("section") or "overview").strip()
if criterion and not criterion.startswith("criterion_"):
    criterion = "criterion_" + criterion

result = PREVIEW_DATA.get(criterion)
if result:
    payload = dict(result)
    payload["active_section"] = section
    payload["section"] = result.get("sections", {}).get(section) or result.get("sections", {}).get("overview")
    frappe.response["message"] = {
        "ok": True,
        "version": "1.8.4",
        "demo_only": True,
        "data": payload
    }
else:
    frappe.response["message"] = {
        "ok": False,
        "version": "1.8.4",
        "demo_only": True,
        "error": "Dummy preview data is available only for Criteria 1–3 and 6–7."
    }
